# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  ENVIRONMENT: deploy

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup-secrets:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: ${{ env.ENVIRONMENT }}
    steps:
      - name: Set var
        run: echo "MY_SECRET=${{ secrets.MYSECRET }}" >> $GITHUB_ENV
      - name: Get var
        run: echo "MY_SECRET=$MY_SECRET"

  build:
    environment: deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Log it
        run: echo "  MY_SECRET=${{ secrets.MYSECRET }}"
  build2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Get var
        run: echo "MY_SECRET=$MY_SECRET"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
